package com.timachado.fiolab

import android.content.Intent
import android.util.Base64
import androidx.activity.ComponentActivity
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.junit4.createEmptyComposeRule
import androidx.compose.ui.test.onNodeWithText
import androidx.core.content.FileProvider
import androidx.test.core.app.ActivityScenario
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import java.io.File
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class ExternalOpenIntentSmokeTest {
    @get:Rule
    val composeRule =
        createEmptyComposeRule()

    @Test
    fun actionViewOpensPesDirectlyInViewer() {
        val context =
            InstrumentationRegistry
                .getInstrumentation()
                .targetContext

        val sharedDir =
            File(
                context.cacheDir,
                "shared"
            ).apply {
                mkdirs()
            }

        val matrixFile =
            File(
                sharedDir,
                "random1.pes"
            )

        matrixFile.writeBytes(
            Base64.decode(
                SAMPLE_PES_BASE64,
                Base64.DEFAULT
            )
        )

        val uri =
            FileProvider.getUriForFile(
                context,
                context.packageName +
                    ".fileprovider",
                matrixFile
            )

        val intent =
            Intent(
                context,
                MainActivity::class.java
            ).apply {
                action =
                    Intent.ACTION_VIEW
                data =
                    uri
                addFlags(
                    Intent.FLAG_ACTIVITY_NEW_TASK or
                        Intent.FLAG_GRANT_READ_URI_PERMISSION
                )
            }

        ActivityScenario
            .launch<MainActivity>(
                intent
            )
            .use {
                composeRule.waitUntil(
                    timeoutMillis =
                        15_000
                ) {
                    composeRule
                        .onAllNodesWithText(
                            "random1.pes"
                        )
                        .fetchSemanticsNodes()
                        .isNotEmpty()
                }

                composeRule
                    .onNodeWithText(
                        "random1.pes"
                    )
                    .assertIsDisplayed()
            }
    }

    private companion object {
        const val SAMPLE_PES_BASE64 =
            """I1BFUzAwMDH8AQAAAQABAAEA//8AAAcAQ0VtYk9uZQAAAAAAAAAAAAAAAAAA
AAAAAIA/AAAAAAAAAAAAAIA/AKADRACQuUQBAAAAAACzA8kDAAAAAAAAAAAU
AP//AAAHAENTZXdTZWcBACcAAgDfASv+QAFj/gOAAAAnAAMAQAFj/ioCL/9P
A3b9A4ABAC4AAgBPA3b9fwGC/AOAAAAuAAMAfwGC/DEBX/9OAwX9A4ABADcA
AgBOAwX9rABZ/wOAAAA3AAMArABZ/2kDXv0AALv+A4ABAAoAAgAAALv+QgJv
/wOAAAAKAAMAQgJv/7MDEv4BAzf8A4ABAC0AAgABAzf8BgJc/QOAAAAtAAMA
BgJc/SoBbP+QA7f8A4ABADAAAgCQA7f8AQG2/gOAAAAwAAMAAQG2/jYArv+2
AXf8A4ABAAoAAgC2AXf8RwF6/QOAAAAKAAMARwF6/X4Bb/4dAYz9A4ABABMA
AgAdAYz9FwKp/AOAAAATAAMAFwKp/IkBBf6qAAAAA4ABACMAAgCqAAAA8QCn
/QOAAAAjAAMA8QCn/ZsCu/5DAJX+A4ABADoAAgBDAJX+QgPR/gOAAAA6AAMA
QgPR/iEBtvy6AZP9CgAAACcAAgAuAAQANwAGAAoACAAtAAoAMAAMAAoADgAT
ABAAIwASADoAAAAAAExBOlVudGl0bGVkICAgICAgICANICAgICAgICAgICAg
/wAGJiAgICAgICAgICAgIAknLjc9LTAKEyM6ICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgAADQAAAx//CzA8kD4AGw
AZHfkfSvYaA4AAAAAIDqgMyBJY5H/rACrjCvDAAAAACPsoLdgh2Npv6wAa1e
olQAAAAAgr2OBYyXgV3+sAKiQqC0AAAAAIFxjqOPTo4l/rABrwWhJQAAAACP
JIIQgmaNS/6wAq1xof8AAAAAjzWA+IGAjMn+sAGvkaEDAAAAAIA3gPWPn48d
/rACoPqvHQAAAACPcoFcjyGB+/6wAaBHracAAAAAgaqBFI2oj9r+sAKi/6A8
AAAAAI3fjeWAmYDd/wAAAAAAAPD/////DwgAAAAEEAQAAAAAIAIAUAAAQAIA
AAAAQAIAAgSAQAIAAAAAQAIAAAAAQAIAAAAgQAIAAAAAQAIAAAAAQAIAAAJA
QAIABgAgQAKAQAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAIAAAQQIAAAAAQAIA
AAAAQAIAFAAAQAIAAAAAQAICAAAAQIIAAUAAQAIAAAAQQAIAAAAAQAIAAAAA
QAIAAAQAQAIAAAAAQAIgBggAQAIAAAAAQAIAAAAAQAICAAAAQAQAAAAAIAgA
AAAAEPD/////DwAAAAAAAAAAAAAAAPD/////DwgAAAAAEAQAAAAAIAIAAAAA
QAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIA
AAAAQAIAAAAQQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAA
QAIAAAAAQAIABAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIA
AAAAQAIAAAQAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAQAAAAA
IAgAAAAAEPD/////DwAAAAAAAAAAAAAAAPD/////DwgAAAAAEAQAAAAAIAIA
AAAAQAIAEAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAQQAIAAAAAQAIAAAAA
QAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIA
AAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAA
QAIAAAAAQAIAAAAAQAIAAAAAQAIABAAAQAIAAAAAQAIAAAAAQAIAAAAAQAQA
AAAAIAgAAAAAEPD/////DwAAAAAAAAAAAAAAAPD/////DwgAAAAAEAQAAAAA
IAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIA
AAAAQAIAAAAgQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAA
QAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQIIAAAAAQAIAAAAAQAIA
AAAAQAIAAAAAQAIAAAAAQAIgAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAA
QAQAAAAAIAgAAAAAEPD/////DwAAAAAAAAAAAAAAAPD/////DwgAAAAEEAQA
AAAAIAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAA
QAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIA
AAAAQQIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAA
QAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAgAQAIAAAAAQAIAAAAAQAIA
AAAAQAQAAAAAIAgAAAAAEPD/////DwAAAAAAAAAAAAAAAPD/////DwgAAAAA
EAQAAAAAIAIAAAAAQAIAAAAAQAIAAABAQAIAAAAAQAIAAAAAQAIAAAAAQAIA
AAAAQAIAAAAAQAIAAAIAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAA
QAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIA
AAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIABAAAQAIAAAAAQAIAAAAA
QAIAAAAAQAQAAAAAIAgAAAAAEPD/////DwAAAAAAAAAAAAAAAPD/////DwgA
AAAAEAQAAAAAIAIAQAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAA
QAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIA
AAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAQAA
QAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIC
AAAAQAIAAAAAQAQAAAAAIAgAAAAAEPD/////DwAAAAAAAAAAAAAAAPD/////
DwgAAAAAEAQAAAAAIAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIA
AAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIACAAAQAIAAgAAQAIAAAAAQAIAAAAA
QAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAEAAAQAIAAAAAQAIAAAAAQAIA
AAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAA
QAIAAAAAQAIAAAAAQAQAAAAAIAgAAAAAEPD/////DwAAAAAAAAAAAAAAAPD/
////DwgAAAAAEAQAAAAAIAIAAAAAQAIAAAAAQAIAAAQAQAIAAAAAQAIAAAAA
QAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIA
AAAAQAIAAAAAQAIAIAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAA
QAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIA
AAAAQAIAAAAAQAIAAAAAQAQAAAAAIAggAAAAEPD/////DwAAAAAAAAAAAAAA
APD/////DwgAAAAAEAQAAAAAIAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIA
AAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAQAA
QAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIE
AAAAQAIAAEAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAA
QAIAAAAAQAIAAAAAQAIAAAAAQAQAAAAAIAgAAAAAEPD/////DwAAAAAAAAAA
AAAAAPD/////DwgAAAAAEAQAAAAAIAIAAAAAQAIAAAAAQAIAAgAAQAIAAAAA
QAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAQAAAQAIA
AAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAA
QAIAAAAAQAIAAAAAQAIAAAAQQAIAAAAAQAIAAAAAQAIAAAAAQAIAAAAAQAIA
AAAAQAIAAAAAQAIAAAAAQAIAAAAAQAQAAAAAIAgAAAAAEPD/////DwAAAAAA
AA==
"""
    }
}
